# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9a54f46bbd8e9c842f89dae3dcff8b0bf794289028408e3621602e27010471b56b4a2f24bf3f617458b666727e8168b85111ac0cc5b5669f21412ebbbfc9325

test:
  secret_key_base: e714f2aa45926fc3d9fe6b52ece5c7d75018cc736b1da630d9c201a668a700f6d9b656e35614b2bc31811569a5af454aaaaec1d8bbccbdc9667d23b7ce962010

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
